---
# tasks file for hemanth22.ci
- name: Ensuring maven and git is installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - maven
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
  tags:
    - ci

- name: Creating a test directory
  file:
    path: "{{ ci_path }}"
    state: directory
    mode: 0777
  register: foldercreate
  tags:
    - ci

- name: Cloning a repository
  git:
    repo: "{{ ci_repo }}"
    dest: "{{ ci_path }}"
    clone: true
    version: "{{ ci_branch }}"
  register: cloning
  when: foldercreate.changed
  tags:
    - ci
    - skip_ansible_lint
  notify:
    - Compile program with maven
    - Testing program with maven
    - Packing program with maven

- name: Destroying test directory
  file:
    path: "{{ ci_path }}"
    state: absent
    force: true
  tags:
    - destroy
