---
# tasks file for hemanth22.ci
- name: Ensuring maven and git is installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - maven
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
  tags:
    - ci

- name: Creating a test directory
  file:
    path: "{{ ci_path }}"
    state: directory
    mode: 0777
  register: foldercreate
  tags:
    - ci

- name: Cloning a repository
  git:
    repo: "{{ ci_repo }}"
    dest: "{{ ci_path }}"
    clone: true
    version: "{{ ci_branch }}"
  register: cloning
  when: foldercreate.changed
  tags:
    - ci
    - skip_ansible_lint

- name: Compile program with maven
  command: "{{ maven_create_command }}"
  args:
    chdir: "{{ ci_path }}"
  when: cloning.changed
  tags:
    - ci
    - skip_ansible_lint

- name: Testing program with maven
  command: "{{ maven_test_command }}"
  args:
    chdir: "{{ ci_path }}"
  when: cloning.changed
  tags:
    - ci
    - skip_ansible_lint

- name: Packing program with maven
  command: "{{ maven_artifacts_command }}"
  args:
    chdir: "{{ ci_path }}"
  when: cloning.changed
  tags:
    - ci
    - skip_ansible_lint

- name: Destroying test directory
  file:
    path: "{{ ci_path }}"
    state: absent
  tags:
    - destroy
