---
# tasks file for hemanth22.ci
- name: Ensuring maven and git is installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - maven
  when: ansible_distribution == 'CentOS'
  tags:
    - ci
    - molecule-idempotence-notest

- name: Creating a test directory
  file:
    path: "{{ ci_path }}"
    state: directory
    mode: 0777
  register: foldercreate
  tags:
    - ci
    - molecule-idempotence-notest

- name: Cloning a repository
  git:
    repo: "{{ ci_repo }}"
    dest: "{{ ci_path }}"
    clone: true
    version: "{{ ci_branch }}"
  register: cloning
  when: foldercreate.changed
  tags:
    - ci
    - skip_ansible_lint
    - molecule-idempotence-notest

- name: Compile with maven
  command: "{{ maven_create_command }}"
  args:
    chdir: "{{ ci_path }}"
    creates: "{{ ci_path }}"
    warn: false
  when: cloning.changed
  tags:
    - ci
    - skip_ansible_lint
    - molecule-idempotence-notest

- name: Testing with maven
  command: "{{ maven_test_command }}"
  args:
    chdir: "{{ ci_path }}"
    creates: "{{ ci_path }}"
    warn: false
  when: cloning.changed
  tags:
    - ci
    - skip_ansible_lint
    - molecule-idempotence-notest

- name: Packing with maven
  command: "{{ maven_artifacts_command }}"
  args:
    chdir: "{{ ci_path }}"
    creates: "{{ ci_path }}"
    warn: false
  when: cloning.changed
  tags:
    - ci
    - skip_ansible_lint
    - molecule-idempotence-notest

- name: Destroying test directory
  file:
    path: "{{ ci_path }}"
    state: absent
    force: true
  tags:
    - destroy
    - molecule-idempotence-notest
